### ISSUE TITLE
Problems met when I followed the guidance

### ISSUE THREAD

**Issue by frank-haomeng-wang** [Ackee-Blockchain/trdelnik#61]
Hi there! Thank you so much for creating this library! However, I had some problems when I tried to follow the Readme instructions and use the library: 

I downloaded the trdelnik-sandbox-cli from the crates.io and did the init, but after that the `trdelink test` command doesn't work because it doesn't find the client and program client inside the Cargo.toml in the created trdelnik tests folder. I now manually copyed the client from the github code, added a lib.rs in test folder, and comment out the program client line, but all the example codes ignored the tests. Do you have any suggestions for this situation?

**Comment by stefanprokopdev** [comment]
Hey @frank-haomeng-wang

You can try to install the new version of the sandbox. There some new features, so you probably would need to change something but it should be working. Let me know if it's working :slightly_smiling_face:

**Comment by stefanprokopdev** [comment]
So finally, the `trdelnik-cli` has been released, you can install it `cargo install trdelnik-cli`.

**Comment by frank-haomeng-wang** [comment]
@stefanprokopdev Thank you so much for your help! I have test it and I believe it should be working. The reason I use "should" is because am using anchor-lang 25.0 as well as solana 1.10.31, along with some functions in the latest versions. I still have to resolve these issues in order to use tridelnik. Thanks you so much for your help!

**Comment by stefanprokopdev** [comment]
Hey @frank-haomeng-wang

it would be nice if you inform me about the cooperation between trdelnik and newer versions of anchor and Solana. If it's working well together.

Thank you and have great weekend!

**Comment by stefanprokopdev** [comment]
Thank you for your response! If something is wrong, let us know about it. I am closing the issue, thanks!
