### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by acamill** [Ackee-Blockchain/trdelnik#91]
Hello, guys. Did console still planned to eventually come?

Also is this project still actively developed or just in maintenance mode?

Cheers and thanks for what you did already

cf: `Q3/22 Trdelnik console available`

**Comment by Ikrk** [comment]
Hi acamill and thanks for your interest!
The roadmap is not updated. Currently we do not plan to implement the console, as there is already good enough alternative - the anchor shell command... 

However we plan to release an update to support Anchor 0.28.0 soon and hopefully shortly after that also first preview version of the fuzzer!

**Comment by acamill** [comment]
Ha sweet! I've upgraded my version locally to 0.28.0, and while waiting for your answer I implemented a client using anchor_client indeed. Looking forward to fuzzer, thanks guys!
